### ISSUE TITLE
Should depend on the glibc version of iconv in Linux and no local package should be installed

### ISSUE THREAD

**Issue by sambitdash** [nalimilan/StringEncodings.jl#18]
GNU libc has iconv in-built. If available in the platform that should be used instead of installing a local libiconv. Some of the discussion is available in the issue #16.

**Comment by nalimilan** [comment]
You said on the other issue:
> Yes. But the build.jl may need changes so that it does not download the libiconv in case the functionality exists. Seems the current provides directive is not honored as in Linux the debian package manager does not show libiconv as a registered package (it's subsumed into glibc). So one may need to check for a linking symbol like a library version or iconv function call.

The existing build.jl is supposed to check whether libc provides the needed functions first. And indeed on most Linux distributions there's no need to install the GNU libiconv package as glibc is enough. Could you check what happens if you remove `validate = validate_iconv`? If that works, then the validation of the function's behavior is failing for some reason.

**Comment by sambitdash** [comment]
Issue is closed with the merger of #19.
